name: Example
on:
 push:
  branches: [ master ]
 
 pull_request:
   branches: [ master ]
 
jobs:
 pull_request:
   runs-on: ubuntu-latest
 
   env:
     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_KEY_ID }}
     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET }}
 
   steps:
   - name: Checkout
     uses: actions/checkout@v2
