name: Example pipeline
on:
 push:
  branches: [master]
 pull_request:
   branches: [master]

permissions:
 id-token: write
 contents: read

jobs:
 pull_request:
   runs-on: ubuntu-latest

   env:
     AWS_DEFAULT_REGION: us-east-1

   steps:
   - name: configureawscredentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
       role-to-assume: arn:aws:iam::298848018041:role/my-github-role
       role-session-name: samplerolesession
       aws-region: ${{env.AWS_DEFAULT_REGION}}

   - name: Checkout
     uses: actions/checkout@v2
     #test

 
